from __future__ import annotations
from typing import Protocol, AsyncIterator
from .models import NormalizedEvent

class BlockchainAdapter(Protocol):
    chain_name: str
    async def health(self) -> bool: ...
    async def stream_events(self) -> AsyncIterator[NormalizedEvent]: ...

class BlockReader(Protocol):
    async def latest_height(self) -> int: ...
    async def get_transaction(self, transaction_id: str) -> dict: ...
